spring.application.name=stock-option-scraper

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/stock-option-data
spring.datasource.username=postgres
spring.datasource.password=S8r8s0t8
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.data.jpa.repositories.enabled=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Debugging
spring.jpa.show-sql=false
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.results=TRACE

# App settings
app.yf-option-scraper.url=https://finance.yahoo.com/quote/{symbol}/options/?date={epoch}
app.rate-scraper.url=https://www.federalreserve.gov/releases/h15/
app.override-time-frame=false
app.output-console-log-verbose=false
app.symbol.default=^SPX
app.run-interval.minutes=15
app.max-strike-range=25