spring.application.name=stock-option-scraper

#spring.datasource.url=jdbc:mysql://localhost:3306/DB
#spring.datasource.username=your_username
#spring.datasource.password=your_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.scraper.url=https://finance.yahoo.com/quote/{symbol}/options/?date={date}
app.override-time-frame=true
app.symbol.default=^SPX
app.run-interval.minutes=15
